

AMD64_OBJECTS=\
 $(OBJ_PATH)\$O\miniport.obj \
 $(OBJ_PATH)\$O\passthru.obj \
 $(OBJ_PATH)\$O\protocol.obj \


_RES_FILE=$(OBJ_PATH)\$O\passthru.res
PRECOMPILED_INCLUDE_BASENAME=precomp.h




# lowercased
BASEDIR=c:\winddk\7600.16385.1
OBJECT_ROOT=c:\winddk\7600.16385.1
MAKEDIR_LOWERCASE=e:\item\macmanager\v2.0\src\firewallex
OBJ_PATH=e:\item\macmanager\v2.0\src\firewallex
CONCURRENT_MIDL=0
CONCURRENT_MANIFEST_BUILD=0
