//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SafeDiskManager.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_VERSION                     101
#define IDS_TAB_DIR                     102
#define IDD_USBMANAGER_DIALOG           102
#define IDS_TAB_VERSION                 103
#define IDS_CHILD_NAME                  104
#define IDS_TAB_CMD                     105
#define ID_INDICATOR_IP                 106
#define ID_INDICATOR_PATH               107
#define ID_INDICATOR_SIZE               108
#define IDS_TAB_PASSWORD                109
#define ID_INDICATOR_LAST_LOGIN         110
#define IDS_TAB_SCREEN                  111
#define IDS_TAB_PROCESS                 112
#define IDS_TAB_SERVICE                 113
#define IDS_TAB_KEYBOARD                114
#define IDS_TAB_NETWORK                 115
#define IDS_TAB_CONTROL                 116
#define IDS_MENU_PROCESS                117
#define IDS_TAB_LOCK                    118
#define IDR_POPUP_EDIT                  119
#define IDS_TAB_BLACKWHITE_LIST         119
#define ID_STATUSBAR_PANE1              120
#define IDS_TAB_CONTROL_DEV             120
#define ID_STATUSBAR_PANE2              121
#define IDS_TAB_CONTROL_STORAGE         121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDS_TAB_CONTROL_SYSTEM          126
#define IDS_TAB_FILE                    127
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDI_LOOK_ICON                   129
#define IDS_TAB_CONTROL_PANEL           129
#define IDR_SafeDiskManagerTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDI_BLANK_ICON                  131
#define IDS_TAB_HOSTINFO                131
#define IDS_WINDOWS_MANAGER             132
#define IDD_URL_DIALOG                  132
#define ID_VIEW_FILEVIEW                133
#define IDS_TAB_PROGRAM                 133
#define ID_VIEW_CLASSVIEW               134
#define IDC_LOOK_CUR                    134
#define IDD_WINDOW_DIALOG               134
#define IDS_TITLE                       134
#define ID_PROPERTIES                   135
#define IDD_DIALOG_REG_CHECK            135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define IDD_LOGIN_MODIFY_DIALOG         139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define IDD_UDISK_DIALOG                140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDB_BITMAP_CCSB                 150
#define ID_SORTPROPERTIES               151
#define IDB_BITMAP_CZXT                 151
#define ID_PROPERTIES1                  152
#define IDB_BITMAP_DKSZ                 152
#define ID_PROPERTIES2                  153
#define IDB_BITMAP_RJSZ                 153
#define ID_EXPAND_ALL                   154
#define IDB_BITMAP_WLXW                 154
#define IDS_FILE_VIEW                   155
#define IDB_BITMAP_ZNSB                 155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDD_UDISK_LOGIN_DIALOG          171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDD_CONTROL_STORAGE_DIALOG      173
#define IDR_POPUP_EXPLORER              174
#define IDD_CONTROL_DEV_DIALOG          174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDB_CONNECT_VIEW                185
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_DIALOG_APP_CONFIG           310
#define IDD_DIALOG_SCREEN               311
#define IDD_DIALOG_PROPERTIES           312
#define IDD_DIALOG_CONTROL              313
#define IDR_EXE_VNC_CLIENT              313
#define IDD_DIALOG_POLICY               314
#define IDD_DIALOG_LOCK                 315
#define IDD_DIALOG_BLACKWHITE_LIST      316
#define IDB_BITMAP_TOPTITLE             316
#define IDD_DIALOG_USER_ADD             317
#define IDD_DIALOG_USER_MODIFY          318
#define IDR_BIN_WSDL                    318
#define IDR_MENU_CHILD                  319
#define IDD_DIALOG_USER_LOGIN           319
#define IDR_BIN_CONFIG                  319
#define IDR_MENU_CHILD_TAB              320
#define IDD_DIALOG_USER_MANAGE          320
#define IDB_BITMAP_COMPUTER_ONLINE      320
#define IDR_MENU_CHILD_WND              321
#define IDD_WINDOW_RULE_DIALOG          321
#define IDB_BITMAP_COMPUTER_OFFLINE     321
#define IDD_CONTROL_SYSTEM_DIALOG       322
#define IDB_BITMAP_COMPUTER_ONLINE1     322
#define IDB_BITMAP_COMPUTER_ONLINE_LOCKED 322
#define IDD_DIALOG_NETWORK              323
#define IDD_DIALOG_PROGRAM              324
#define IDI_ICON_ERROR                  325
#define IDS_TAB_NETWORK_RATE            325
#define IDI_ICON_INFO                   326
#define IDR_MENU1                       327
#define IDR_MENU_POPUP_HOSTINFO         327
#define IDD_DIALOG_MODIFY_COMMENT       328
#define IDD_DIALOG_UPGRADE              329
#define IDD_DIALOG_POLICY_EDIT          330
#define IDB_PNG1                        330
#define IDD_GROUP_DIALOG                331
#define IDD_GROUP_LIST_DIALOG           332
#define IDC_EDIT_HOST                   1000
#define IDC_EDIT_HOST_KEY               1000
#define IDC_RADIO_UDISK_DISABLE         1000
#define IDC_RADIO_NORMAL                1000
#define IDC_EDIT_PORT                   1001
#define IDC_BUTTON_SCREEN               1001
#define IDC_BTN_OK                      1001
#define IDC_CHECK_BLUETOOTH             1001
#define IDC_RADIO_BLACK                 1001
#define IDC_EDIT_KEY                    1002
#define IDC_BUTTON_SCREEN2              1002
#define IDC_BUTTON_OPEN                 1002
#define IDC_STATIC_ID                   1002
#define IDC_CHECK_SERIAL                1002
#define IDC_RADIO_SPEC                  1002
#define IDC_EDIT_PAGE                   1003
#define IDC_STATIC_IP_OUT               1003
#define IDC_BUTTON_VNC_VIEW             1003
#define IDC_CHECK_1394                  1003
#define IDC_EDIT_TIMEOUT                1004
#define IDC_STATIC_IP_IN                1004
#define IDC_BUTTON_VNC_CONTROL          1004
#define IDC_CHECK_IRDA                  1004
#define IDC_EDIT_FILE_PAGE              1005
#define IDC_STATIC_USER_IN              1005
#define IDC_CHECK_PCMCIA                1005
#define IDC_LOOK                        1005
#define IDC_EDIT_LOCAL_DIR              1006
#define IDC_STATIC_LAST_LOGIN           1006
#define IDC_CHECK_MODEM                 1006
#define IDC_STATIC_HOSTNAME             1007
#define IDC_CHECK_REGEDIT               1007
#define IDC_BUTTON_RESTART              1008
#define IDC_STATIC_DEVICE_SERIAL        1008
#define IDC_CHECK_DEVMGR                1008
#define IDC_BUTTON_RESTART2             1009
#define IDC_BUTTON_SHUTDOWN             1009
#define IDC_EDIT_USER                   1009
#define IDC_CHECK_GPEDIT                1009
#define IDC_STATIC_HOSTNAME3            1010
#define IDC_STATIC_COMMENT              1010
#define IDC_BUTTON_LOCK                 1010
#define IDC_BUTTON_LOGOFF               1010
#define IDC_CHECK_SAFEMODE              1010
#define IDC_EDIT_COMPANY                1011
#define IDC_BUTTON_UNLOCK               1011
#define IDC_CHECK_TASKMGR               1011
#define IDC_EDIT_NUMBER                 1012
#define IDC_BUTTON_LOCK_AUTO            1012
#define IDC_CHECK_MSCONFIG              1012
#define IDC_CHECK_COMPUTERMGR           1013
#define IDC_EDIT_ID                     1014
#define IDC_CHECK_FORMAT                1014
#define IDC_CHECK_DOS                   1015
#define IDC_CHECK_CD_BOOT               1016
#define IDC_DATETIMEPICKER_START        1017
#define IDC_CHECK_U_BOOT                1017
#define IDC_DATETIMEPICKER_END          1018
#define IDC_CHECK_LAN                   1018
#define IDC_LIST_WIN                    1019
#define IDC_CHECK_KEY_PRTSCN            1019
#define IDC_DATETIMEPICKER_START_DATE   1019
#define IDC_BUTTON_WIN_ADD              1020
#define IDC_CHECK_KEY_ESC               1020
#define IDC_EDIT_WINDOW                 1020
#define IDC_DATETIMEPICKER_END_DATE     1020
#define IDC_EDIT_PASSWORD               1021
#define IDC_BUTTON_WIN_DEL              1021
#define IDC_CHECK_KEY_WIN               1021
#define IDC_EDIT_CLASS                  1021
#define IDC_BUTTON_SET_PASSWORD         1022
#define IDC_LIST_WHITE_WIN              1022
#define IDC_EDIT_PASSWORD2              1022
#define IDC_CHECK_KEY_CTRLALTA          1022
#define IDC_EDIT_AUTO_TIME              1023
#define IDC_BUTTON_WHITE_WIN_ADD        1023
#define IDC_CHECK_CLIPBOARD             1023
#define IDC_EDIT_DESC                   1023
#define IDC_EDIT_IDLE_TIME              1023
#define IDC_BUTTON_SCREEN_AUTO          1024
#define IDC_BUTTON_WHITE_WIN_DEL        1024
#define IDC_CHECK_MAIL                  1024
#define IDC_RADIO_LIST                  1025
#define IDC_RADIO_UDISK_SPEC            1025
#define IDC_RADIO_WHITE_LIST            1026
#define IDC_BUTTON1                     1026
#define IDC_BUTTON_REREG                1026
#define IDC_BUTTON_ADD                  1026
#define IDC_RADIO_UDISK_WRITEPROTECT    1026
#define IDC_BUTTON_SAVE                 1026
#define IDC_BUTTON_SYSTEM_SAVE          1026
#define IDC_BUTTON_SET                  1026
#define IDC_BUTTON_REFRESH              1026
#define IDC_LIST_USER                   1027
#define IDC_CHECK_DISK                  1027
#define IDC_BUTTON_DEL                  1028
#define IDC_RADIO_UDISK_COPYTOCOMPUTER  1028
#define IDC_RADIO_UDISK_PASSWD          1029
#define IDC_BUTTON_DEL2                 1029
#define IDC_CHECK_BLOG                  1030
#define IDC_BUTTON_STORAGE_SAVE         1030
#define IDC_CHECK_FTP                   1031
#define IDC_STATIC_LIMIT                1031
#define IDC_CHECK_QQ_FILE               1032
#define IDC_STATIC_UPLOAD               1032
#define IDC_CHECK_QQ_GROUP_FILE         1033
#define IDC_STATIC_DOWNLOAD             1033
#define IDC_CHECK_QQ_SPEC               1034
#define IDC_EDIT1                       1034
#define IDC_CHECK_WANGWANG_SPEC         1035
#define IDC_CHECK_FILE_TRANS            1036
#define IDC_LIST_UPGRADE                1036
#define IDC_CHECK_CHAT                  1037
#define IDC_BUTTON_UPGRADE              1037
#define IDC_CHECK_PROCESS_BLACKLIST     1038
#define IDC_BUTTON_UPGRADE_SERVICE      1038
#define IDC_CHECK_URL_BLACKLIST         1039
#define IDC_BUTTON_UPGRADE_CONFIG       1039
#define IDC_CHECK_PROCESS_WHITELIST     1040
#define IDC_CHECK_URL_WHITELIST         1041
#define IDC_RADIO_UDISK_ENABLE          1042
#define IDC_CHECK_DEVICE_CELL           1043
#define IDC_CHECK_PHONE_ASSIST          1044
#define IDC_CHECK_NETWORK_WIRED         1045
#define IDC_CHECK_NETWORK_WIRELESS      1046
#define IDC_CHECK_NETWORK_MINI          1047
#define IDC_CHECK_CD_DVD                1048
#define IDC_CHECK_CD_BURN               1049
#define IDC_CHECK_FLOPPY                1050
#define IDC_CHECK_HOTKEY                1051
#define IDC_BUTTON_MOVE_WHITE           1052
#define IDC_BUTTON_MODIFY_HOTKEY        1052
#define IDC_BUTTON_INPORT               1053
#define IDC_BUTTON_UNINSTALL            1053
#define IDC_BUTTON_EXIT                 1055
#define IDC_LIST                        1057
#define IDC_CHECK_AUTO_RUN              1057
#define IDC_LIST_AUTH                   1058
#define IDC_CHECK_USB_LOG               1058
#define IDC_EDIT_PROCESS                1058
#define IDC_BUTTON_HIDE                 1059
#define IDC_BUTTON_USB_LOG              1060
#define IDC_CHECK_SSL                   1061
#define IDC_BUTTON_IMPORT               1062
#define IDC_CHECK_SHARE                 1062
#define IDC_BUTTON_EXPORT               1063
#define IDC_CHECK_IP                    1063
#define IDC_BUTTON_CLEAN                1064
#define IDC_CHECK_TELNET                1064
#define IDC_EDIT_URL                    1065
#define IDC_CHECK_VIR                   1065
#define IDC_STATIC_STORAGE              1066
#define IDC_BUTTON_PHONE_ASSIST_OP      1067
#define IDC_BUTTON_MAIL_OP              1068
#define IDC_BUTTON_DISK_OP              1069
#define IDC_BUTTON_FTP_OP               1070
#define IDC_BUTTON_ADD_U_ID             1071
#define IDC_BUTTON_CD_BURN_OP           1072
#define IDC_BUTTON_CHAT_OP              1073
#define IDC_BUTTON_PROCESS_BLACKLIST_OP 1074
#define IDC_BUTTON_URL_BLACKLIST_OP     1075
#define IDC_BUTTON_PROCESS_WHITELIST_OP 1076
#define IDC_BUTTON_URL_WHITELIST_OP     1077
#define IDC_BUTTON_UDISK_PASSWD         1078
#define IDC_BUTTON_NETWORK_MINI         1079
#define IDC_CHECK_ADD_HTTP              1080
#define IDC_BUTTON_NETWORK_WIRED        1080
#define IDC_BUTTON_NETWORK_WIRELESS     1081
#define IDC_BUTTON_SAVE_IP              1082
#define IDC_BUTTON_BLOG_OP              1083
#define IDC_BUTTON_LAN                  1084
#define IDC_BUTTON_QQ_SPEC              1085
#define IDC_BUTTON_WANGWANG_SPEC        1086
#define IDC_STATIC_CCSB                 1087
#define IDC_STATIC_DKSZ                 1088
#define IDC_STATIC_WLXW                 1089
#define IDC_STATIC_CZXT                 1090
#define IDC_STATIC_ZNSB                 1091
#define IDC_STATIC_RJSZ                 1092
#define IDC_IPADDRESS_START             1093
#define IDC_IPADDRESS_END               1094
#define IDC_CHECK_CREATEUSER            1095
#define IDC_BUTTON_MAN_USER             1097
#define IDC_CHECK_START_HIDE            1098
#define IDC_CHECK_AUTO_LOGIN            1099
#define ID_32771                        32771
#define ID_APP_CONFIG                   32772
#define ID_CHILD_32773                  32773
#define ID_CHILD_REFRESH                32774
#define ID_CHILD_SAVE                   32775
#define ID_CHILD_32777                  32777
#define ID_CHILD_UPDATE                 32778
#define ID_CHILD_32779                  32779
#define ID_CHILD_KILL_PROCESS           32780
#define ID_32781                        32781
#define ID_POLICY                       32782
#define ID_32783                        32783
#define ID_CHILD_DOWNLOAD               32784
#define ID_REMOTE_OPEN                  32784
#define ID_CHILD_UPLOAD                 32785
#define ID_32785                        32785
#define ID_32786                        32786
#define ID_CHILD_CLOSE                  32787
#define ID_VIEW_TOPWND                  32787
#define ID_32788                        32788
#define ID_32789                        32789
#define ID_32790                        32790
#define ID_APP_USER_MODIFY              32791
#define ID_APP_USER_MANAGE              32792
#define ID_32793                        32793
#define ID_123_123                      32794
#define ID_32795                        32795
#define ID_32796                        32796
#define ID_32797                        32797
#define ID_32798                        32798
#define ID_CONTROL_DEV                  32799
#define ID_CONTROL_STORAGE              32800
#define ID_CONTROL_SYSTEM               32801
#define ID_32802                        32802
#define ID_BATCH_LOCK                   32803
#define ID_HOST_32804                   32804
#define ID_HOST_REFRESH                 32805
#define ID_32806                        32806
#define ID_COMMENT                      32807
#define ID_32808                        32808
#define ID_BATCH_UNLOCK                 32809
#define ID_32810                        32810
#define ID_32811                        32811
#define ID_BATCH_UPGRADE                32812
#define ID_32813                        32813
#define ID_POLICY_EDIT                  32814
#define ID_32815                        32815
#define ID_32816                        32816
#define ID_32817                        32817
#define ID_32818                        32818
#define ID_32819                        32819
#define ID_GROUP_ADD                    32820
#define ID_GROUP_EDIT                   32821
#define ID_GROUP_DEL                    32822
#define ID_ADDTO_GROUP                  32823
#define ID_GROUP_ADDTO                  32824
#define ID_GROUP_CREATE                 32825
#define ID_32826                        32826
#define ID_32827                        32827
#define ID_BATCH_AUTO                   32828
#define ID_32829                        32829
#define ID_VIEW_DEFAULT_ALLOW           32830

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        338
#define _APS_NEXT_COMMAND_VALUE         32831
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
